/* 
3 - ELABORE UM ALGORITIMO QUE CALCULE O QUE DEVE SER PAGO 
POR UM produto, CONSIDERANDO O PREÇO NORMAL DE ETIQUETA E
A ESCOLHA DA CONDIÇÃO DE PAGAMENTO.

 UTILIZE OS CODIGOS  DE TABELA A SEGUIR PARA LER QUAL A 
 CONDIÇÃO DE PAGAMENTO ESCOLHIDA E EFETUAR O CÁLCULO ADEQUADO.
 
 
 CÓDIGO - CONDIÇÃO DE PAGAMENTO:
 1 - À VISTA DÈBITO, RECEBE 10% DE DESCONTO;
 2 - À VISTA NO DINHEIRO OU PIX, RECEBE 15% DE DESCONTO;
 3 - EM DUAS VEZES, PREÇO NORMAL DE ETIQUETA SEM JUROS;
 4 - ACIMA DE DUAS VEZES, PREÇO NORMAL DE EQIQUETA MAIS JUROS DE 10%

*/

const produto = 500;
const TipoPay = 4;

if (TipoPay === 1) {
    console.log("FORMA DE PAGAMENTO DÉBITO ESCOLHIDA. DESCONTO DE 10% APLICADO : R$",produto - (produto * 0.1) );

} else if (TipoPay === 2) {
    console.log("FORMA DE PAGAMENTO DINHEIRO/PIX ESCOLHIDA. DESCONTO DE 15% APLICADO : R$",produto - (produto * 0.15));

} else if (TipoPay === 3) {
    console.log("FORMA DE PAGAMENTO EM DUAS VEZES ESCOLHIDA. SEM DESCONTO: R$",produto);

} else if (TipoPay === 4) {
    console.log("FORMA DE PAGAMENTO ACIMA DE 2 VEZES ESCOLHIDA. ACRÉSCIMO DE 10% APLICADO :", produto + (produto * 0.1));
    
}